app_public:
    path:     /
    defaults: { _controller: AppPublicBundle:Welcome:welcome }

app_install:
    path: /install
    defaults: { _controller: AppPublicBundle:Install:install }

app_signUp:
    path: /install/sign-up
    defaults: { _controller: AppPublicBundle:Install:signUp }

app_install_ajax:
    path: /installment
    defaults: { _controller: AppPublicBundle:Ajax\Install:install}
